apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: helm-demo
    project: roboshop
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      purpose: helm-demo
      project: roboshop
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: helm-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}